### PR TITLE
Add CocoaPods support

### LINKED ISSUE #1: [question] init(protobuf: )
This library looks awesome!

I was wondering if you could explain briefly how Swift structs are initialized with Data. There must be some magic going on there to make it dynamic. 

Thanks!

### PR DESCRIPTION
**Pull request by radex**
This resolves #1.

There's just one problem before this can just work: I named the Pod "SwiftProtobufRuntime", but the generated `.pb.swift` files do `import Protobuf` — they think this library should be called just "Protobuf".

There's a few possible solutions:

1. I could rename the Pod to "Protobuf". However, there already exists a Pod [named Protobuf](https://cocoapods.org/pods/Protobuf). If Apple isn't interested in pushing the pod to the CocoaPods trunk, this would work fine. But it would still be confusing to users, and if someone has an existing iOS app that uses the Protobuf pod, they couldn't also use *this* library.
2. An option could be added to `swift-protobuf-plugin` to customize [the generated import](https://github.com/apple/swift-protobuf-plugin/blob/6319faae266f2e59e7b9ffc64bb97587ed2ae3ab/Sources/protoc-gen-swift/FileGenerator.swift#L264), so people using CocoaPods or already using Protobuf in their apps (with other libraries) could resolve the naming conflict
3. The runtime module name could be changed to something unambiguous, like `ProtobufSwift` or `ProtobufRuntime` for everyone.
4. I _think_ it should be possible to customize the Podspec so that a module name "Protobuf" is generated, while the Pod itself is still called "SwiftProtobufRuntime" — but I'm still working out how to do that exactly ;)

WDYT?

### CODE REVIEW

**Comment by jcanizales** [comment]
My 2c:

* Option 1 would indeed be confusing :)

* Option 4 is possible in ObjC and C with the podspec attribute `module_name`. I haven't tried it with Swift sources, but I imagine it works the same. It's what I did for [gRPC-Core.podspec](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L61) and [BoringSSL.podspec](https://github.com/grpc/grpc/blob/master/src/objective-c/BoringSSL.podspec#L81), that needed to generate frameworks called `grpc` and `openssl` respectively. It still would make it impossible to use the Swift and ObjC runtimes in the same app, which is unfortunate.

* I thought option 2 would face [the same problem as the ObjC version](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/objectivec/objectivec_helpers.cc#L926): Because the runtime includes generated protos ([empty.proto](https://github.com/apple/swift-protobuf-runtime/blob/master/Sources/Protobuf/empty.pb.swift) etc.), that fixes the name of the module. But none of those generated files `import Protobuf`! Maybe they were hand-edited after generation?

My opinion is `ProtobufSwift` would be the simplest option. We already have libraries named like `RxSwift`, so it wouldn't be an outlier.

**Comment by radex** [comment]
Okay, I added `module_name` option to the Podspec (as @jcanizales and a few others suggested), so the Pod generates a module name "Protobuf" and it just works.

I'd still suggest considering options (2) and (3), but the PR is mergeable as it is ;)

**Comment by tbkka** [comment]
@jcanizales :  The generated files in the runtime library are in fact edited to remove the import statements.  See https://github.com/apple/swift-protobuf-runtime/blob/master/Makefile#L95

**Comment by tbkka** [comment]
I'll see about renaming the module to "SwiftProtobuf".  That will be a little disruptive in the short-term, but seems the best long-term fix.  I'd like to do that before we merge this, if that's okay.  I'll get to it soon.

**Comment by tbkka** [comment]
I just committed the name change; the module is now called 'SwiftProtobuf'.

Please update your merge request accordingly and I'll merge it.

Thanks!

**Comment by radex** [comment]
Thank you — 'SwiftProtobuf' makes a ton of sense!

I updated the Podspec and Readme — should be good to merge!

**Comment by tbkka** [comment]
I've merged this, but we may need to update it after Issue #8 gets finished.

**Pull request merged**
